public with sharing class CDICData_PA {
    public CDICData_Address_ACtr addressCountry;
    public CDICData_Address_ACnt addressCounty;
    public CDICData_Address_AL addressLocality;
    public CDICData_Address_AR addressRegion;
    public CDICData_Description geographicalPrecision;
    public Boolean isManufacturingLocation;
    public Boolean isRegisteredAddress;
    public Boolean isResidentialAddress;
    public CDICData_Description language;
    public String latitude;
    public String longitude;
    public String postalCode;
    public CDICData_Description postalCodePosition;
    public CDICData_Address_SA streetAddress;
    public String streetName;
    public String streetNumber;
}