/**
 * Trigger Handler for the Account SObject. This class implements the ITrigger
 * interface to help ensure the trigger code is bulkified and all in one place.
 */
public class OportunidadHandler implements ITrigger
{
    /**
	*	Listas y mapas de caché
	**
	*	- La referencia se pierde al reinicializar
	**/
	 Map<Id, Account> cuentasOportunidades = new Map<Id, Account>();

    // Constructor
    public OportunidadHandler() {}
 
    /**
     * bulkBefore
     *
     * These methods are called prior to execution of a BEFORE or AFTER trigger. Use this to cache
     * any data required into maps prior execution of the trigger.
     * Any new SOQL operation should be included in these methods (bulkBefore or bulkAfter)
     */
    public void bulkBefore(list<SObject> newList, map<Id,SObject> oldMap) 
	{ 
		if (newList != null)
		{
			cuentasOportunidades = OportunidadUtil.recuperaCuentasDeOportunidades( newList );
		}
		
	}
    
    public void bulkAfter(list<SObject> newList, map<Id,SObject> oldMap) { }
    
    /**
     * These methods ara called for records to be processed during a BEFORE 
     * trigger.
     */
    public void beforeInsert(list<SObject> newList)
    {
        System.debug('----> OportunidadHandler beforeInsert');
        OportunidadUtil.asociarAreaComercial(newList);
        OportunidadUtil.asociarObjetivoCalculadoNuevaOp(newList);
		OportunidadUtil.generarCodigoOportunidad( newList, cuentasOportunidades );
    }
    
    public void beforeUpdate(list<SObject> newList, map<Id,SObject> oldMap)
    {
        System.debug('----> OportunidadHandler beforeUpdate newList/oldMap:' + newList + '/' + oldMap);
        OportunidadUtil.asociarObjetivoCalculadoActualizar(newList, (Map<Id, Opportunity>)oldMap);
        OportunidadUtil.asociarAreaComercial(newList);
    }
    
    public void beforeDelete(map<Id,SObject> oldMap) { }
    
    /**
     * These methods ara called for records to be processed during a AFTER 
     * trigger.
     */ 
    public void afterInsert(list<SObject> newList) { }
     
    public void afterUpdate(list<SObject> newList, map<Id,SObject> oldMap) { }
     
    public void afterDelete(map<Id,SObject> oldMap) { }
     
    /**
     * andFinally
     *
     * This method is called once all records have been processed by the trigger. Use this
     * method to accomplish any final operations such as creation or updates of other records.
     * Any new DML operation should be included in this method
     */
    public void andFinally() 
	{ 
		RecordCounterUtil.contadorCommit();
	}

}